/**********************************************************************************************************************
 * \file Cpu2_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"

#include "XinDongLib/Interrupts.h"
#include "XinDongLib/Intercore.h"
#include "XinDongLib/Bluetooth.h"
#include "XinDongLib/Display.h"
#include "XinDongLib/Encoder.h"
#include "XinDongLib/IMU.h"
#include "XinDongLib/IO.h"
#include "XinDongLib/Movements.h"
#include "XinDongLib/Serial.h"
#include "XinDongLib/Ultrasonic.h"
#include "XinDongLib/Time.h"
#include "XinDongLib/ADC.h"
#include "XinDongLib/PID.h"
#include "XinDongLib/CV.h"

#include <stdio.h>

extern IfxCpu_syncEvent g_cpuSyncEvent;



PID_Handler speed_pid;



sint32 last_encoder_value = 0;
float target_speed = 1000;  // unit:?/////////////////////////////////////////////////////////////

float motor_output = 0;

void core2_main(void) {
	IfxCpu_enableInterrupts();
	/* !!WATCHDOG2 IS DISABLED HERE!!
	 * Enable the watchdog and service it periodically if it is required
	 */
	IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());

	/* Wait for CPU sync event */
	IfxCpu_emitEvent(&g_cpuSyncEvent);
	IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

	// wait for signal to begin initialization
	while (Intercore_InitAllowed() == 0)
		;

	// initialize any module needed
	Serial_Init();
	Bluetooth_Init();
	ADC_Init();
	Ultrasonic_Init();
	OLED_Init();
	MPU6050_Init();
	Encoder_Init();
	Servo_Init();
	Motor_Init();

	// wait for other cores to finish initialization
	Intercore_CPU2_Ready();
	while (Intercore_ReadyToGo() == 0)
		;

	PID_Init(&speed_pid);
	PID_SetParams(&speed_pid, 2.442e-6, 6.923e-4, 2.345e-4);

    // set servo center for straight-line driving
    // 设置舵机中值使得车辆笔直向前运行
    Servo_SetCenter(0.235);/////////////////////////////////////////////////////////////////
    Servo_Set(0);
    // set motor polarity
    Motor_SetPolarity(1);//////////////////////////////////////////////////////////////////
    // delay 5 seconds for DSP in IMU to stablize
    // 延时五秒等待IMU的数字信号处理稳定下来
    Time_Delay(5000);  ////////////////////////////////////////////////////////////////////
    // reset mpu6050 thetaZ angle
    MPU6050_ThetaZ_Reset();
    // start movingk
    Motor_Set(0.15);////////////////////////////////////////////////////////////////////////////
    // main loop
    while (1) {

        CV_Result_t Result = CV_ProcessImage();
        float AngleError = Result.error ;// *some argument
        Servo_Set(AngleError);
    }
}

/* list out all ISR for CPU2 */

void Periodic_1s_ISR(void) {
	;
}

void Periodic_100ms_ISR(void) {
	;
}

void Periodic_10ms_ISR(void) {
	// read ADC result
	ADC_Read();
	// start next conversion
	ADC_Start();
}

void Periodic_PID_ISR(void) {
    sint32 temps32 = Encoder_GetValue();
    if (!IO_DIP_Read(4)) {

        motor_output = PID_Output(&speed_pid, target_speed, (temps32 - last_encoder_value) * 1000.0 / PID_PERIOD_MS);
        last_encoder_value = temps32;
        Motor_Set(motor_output / 1000);
    } else {
        Motor_Set(0);
    }
}

void SWINT_User0_ISR(void) {
	;
}

void SWINT_User1_ISR(void) {
	;
}

void SWINT_User2_ISR(void) {
	;
}

void SWINT_User3_ISR(void) {
	;
}

void Serial_Received(uint8 *dataptr, uint32 length, uint8 tag) {
	switch (tag) {
	case 1:

		break;
	default:
		;
	}
}

void Bluetooth_Received(uint8 *dataptr, uint32 length, uint8 tag) {
	switch (tag) {
	case 1:

		break;
	default:
		;
	}
}

void Reed_Triggered(void) {
	;
}
