/**********************************************************************************************************************
 * \file Cpu2_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"

#include "XinDongLib/Interrupts.h"
#include "XinDongLib/Intercore.h"
#include "XinDongLib/Bluetooth.h"
#include "XinDongLib/Display.h"
#include "XinDongLib/Encoder.h"
#include "XinDongLib/IMU.h"
#include "XinDongLib/IO.h"
#include "XinDongLib/Movements.h"
#include "XinDongLib/Serial.h"
#include "XinDongLib/Ultrasonic.h"
#include "XinDongLib/Time.h"
#include "XinDongLib/ADC.h"
#include "XinDongLib/PID.h"

extern IfxCpu_syncEvent g_cpuSyncEvent;

void core2_main(void) {
	IfxCpu_enableInterrupts();
	/* !!WATCHDOG2 IS DISABLED HERE!!
	 * Enable the watchdog and service it periodically if it is required
	 */
	IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());

	/* Wait for CPU sync event */
	IfxCpu_emitEvent(&g_cpuSyncEvent);
	IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

	// wait for signal to begin initialization
	while (Intercore_InitAllowed() == 0)
		;

	// initialize any module needed
	Serial_Init();
	Bluetooth_Init();
	ADC_Init();
	Ultrasonic_Init();
	OLED_Init();
	MPU6050_Init();
	Encoder_Init();
	Servo_Init();
	Motor_Init();

	// wait for other cores to finish initialization
	Intercore_CPU2_Ready();
	while (Intercore_ReadyToGo() == 0)
		;

	// set servo center for straight-line driving
	// 设置舵机中值使得车辆笔直向前运行
	Servo_SetCenter(0.235);
	Servo_Set(0); /* 1pt */
	// set motor polarity
	Motor_SetPolarity(1);
	// delay 5 seconds for DSP in IMU to stablize
	// 延时五秒等待IMU的数字信号处理稳定下来
	Time_Delay(5000);  /* 1pt */
	// reset mpu6050 thetaZ angle
	MPU6050_ThetaZ_Reset();
	// start moving
	Motor_Set(0.15);

	// encoder_value_start: record the encoder value when an edge starts
	// encoder_value_start: 记录当前这条边开始时的编码器读数
	// edge_num: count the number of edge that is being completed
	// edge_num: 记录正在走过的边数（第一条边、第二条边、……、第八条边、第九条边……）
	sint32 encoder_value_start = 0, edge_num = 1;

	// main loop
	while (1) {
		IO_LED_Toggle(3);

		// MPU6050 update thetaX, thetaY, thetaZ data
		// MPU6050 （IMU芯片）更新角度信息
		MPU6050_Update_Theta();

		// when the encoder has traveled 5000 ticks after current edge starts
		// 当编码器在当前的边开始后总共运行了5000刻以内时
		if ((Encoder_GetValue() - encoder_value_start) < 5000 /* 1pt */) {
		    // drive straight
		    Servo_Set(0);
		}

		// otherwise
		// 否则
		else {
		    // turn left
		    // 向左转
		    Servo_Set(0.5); /* 1pt */

		    // check if the angle is greater or equal to the accumulated angle after the turn at the end of this turn, which is 90deg * # of edges
		    // 检查如果当前角度大于等于转过当前直角弯后应该到达的累计角度，也就是走过的边数乘以九十度
		    if (MPU6050_Get_ThetaZ()/* 1pt */ >= 80 * edge_num) {
		        // record current encoder value
		        encoder_value_start = Encoder_GetValue();
		        // update edge number
		        edge_num++;
		    }
		}
		// show encoder and mpu6050 information on the screen
		OLED_ShowString(0, 0, "Encoder:", OLED_8X16);
		OLED_ShowSignedNum(64, 0, Encoder_GetValue() - encoder_value_start, 5, OLED_8X16);
		OLED_ShowString(0, 16, "thetaZ:", OLED_8X16);
		OLED_ShowFloatNum(64, 16, MPU6050_Get_ThetaZ(), 4, 2, OLED_8X16);
		// update OLED display (very very very important)
		// 更新OLED显示（非常非常非常重要）
		OLED_Update();  /* 1pt */
	}
}

/* list out all ISR for CPU2 */

void Periodic_1s_ISR(void) {
	;
}

void Periodic_100ms_ISR(void) {
	;
}

void Periodic_10ms_ISR(void) {
	;
}

void Periodic_PID_ISR(void) {
	;
}

void SWINT_User0_ISR(void) {
	;
}

void SWINT_User1_ISR(void) {
	;
}

void SWINT_User2_ISR(void) {
	;
}

void SWINT_User3_ISR(void) {
	;
}

void Serial_Received(uint8 *dataptr, uint32 length, uint8 tag) {
    switch (tag) {
    case 1:
        // 假设tag=1表示接收控制指令
        if (dataptr[0] == 'S') {
            Motor_Set(0); // 停止电机
        }
        else if (dataptr[0] == 'F') {
            Motor_Set(0.15); // 前进
        }
        break;
    default:
        ;
    }
}

void Bluetooth_Received(uint8 *dataptr, uint32 length, uint8 tag) {
    switch (tag) {
    case 1:
        // 假设tag=1表示蓝牙遥控指令
        if (length > 0) {
            // 解析蓝牙数据并执行相应操作
            OLED_ShowString(0, 32, "BT:", OLED_8X16);
            OLED_ShowHexNum(32, 32, dataptr[0], 2, OLED_8X16);
            OLED_Update();
        }
        break;
    default:
        ;
    }
}

void Reed_Triggered(void) {
	;
}
