/**********************************************************************************************************************
 * \file Cpu2_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"

#include "XinDongLib/Interrupts.h"
#include "XinDongLib/Intercore.h"
#include "XinDongLib/Bluetooth.h"
#include "XinDongLib/Display.h"
#include "XinDongLib/Encoder.h"
#include "XinDongLib/IMU.h"
#include "XinDongLib/IO.h"
#include "XinDongLib/Movements.h"
#include "XinDongLib/Serial.h"
#include "XinDongLib/Ultrasonic.h"
#include "XinDongLib/Time.h"
#include "XinDongLib/ADC.h"
#include "XinDongLib/PID.h"

#include <stdio.h>

extern IfxCpu_syncEvent g_cpuSyncEvent;

PID_Handler speed_pid;

double kp_min = 0, ki_min = 0, kd_min = 0;
double kp_max = 0.01, ki_max = 0.001, kd_max = 0.001;
double kp = 0, ki = 0, kd = 0;

sint32 last_encoder_value = 0;
float target_speed = 5000;	// unit:?

float motor_output = 0;

char intro[] = "PID Tuning Example:";
char kpstr[] = "Kp:", kistr[] = "Ki:", kdstr[] = "Kd:";

void core2_main(void) {
	IfxCpu_enableInterrupts();
	/* !!WATCHDOG2 IS DISABLED HERE!!
	 * Enable the watchdog and service it periodically if it is required
	 */
	IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());

	/* Wait for CPU sync event */
	IfxCpu_emitEvent(&g_cpuSyncEvent);
	IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

	// wait for signal to begin initialization
	while (Intercore_InitAllowed() == 0)
		;

	// initialize any module needed
	Serial_Init();
	Bluetooth_Init();
	ADC_Init();
	Ultrasonic_Init();
	OLED_Init();
	MPU6050_Init();
	Encoder_Init();
	Servo_Init();
	Motor_Init();
	PID_Init(&speed_pid);

	// wait for other cores to finish initialization
	Intercore_CPU2_Ready();
	while (Intercore_ReadyToGo() == 0)
		;

	// invert motor output
	Motor_SetPolarity(1);
    Servo_SetCenter(0.2);
	Servo_Set(0);


	// print fixed text
	OLED_ShowString(0, 0, intro, OLED_6X8);
	OLED_ShowString(12, 16, kpstr, OLED_6X8);
	OLED_ShowString(12, 28, kistr, OLED_6X8);
	OLED_ShowString(12, 40, kdstr, OLED_6X8);
	// apply change
	OLED_Update();
	Time_Delay(1000);

	// main loop
	while (1) {
		// some code to indicate that the core is not dead
		IO_LED_Toggle(3);
		Time_Delay_us(100000);
		OLED_Update();
	}
}

/* list out all ISR for CPU2 */

void Periodic_1s_ISR(void) {
	;
}

void Periodic_100ms_ISR(void) {
	char buffer[20];
	float pot0, pot1, pot2;
	if (IO_DIP_Read(4)) {
		// read ADC value
		ADC_Read();
		pot0 = ADC_GetVoltage(0);
		pot1 = ADC_GetVoltage(1);
		pot2 = ADC_GetVoltage(2);
		// calculate coefficients
		if (pot0 > 0) {
			kp = kp_min + (kp_max - kp_min) * pot0 / 3.3;
		}
		if (pot1 > 0) {
			ki = ki_min + (ki_max - ki_min) * pot1 / 3.3;
		}
		if (pot2 > 0) {
			kd = kd_min + (kd_max - kd_min) * pot2 / 3.3;
		}
		// apply changes to PID handler
		PID_SetParams(&speed_pid, kp, ki, kd);
		// change displayed number
		sprintf(buffer, " %.3e ", kp);
		OLED_ShowString(30, 16, buffer, OLED_6X8);
		sprintf(buffer, " %.3e ", ki);
		OLED_ShowString(30, 28, buffer, OLED_6X8);
		sprintf(buffer, " %.3e ", kd);
		OLED_ShowString(30, 40, buffer, OLED_6X8);
		// keep sum cleared
		speed_pid.sum = 0;
	}
	sprintf(buffer, " %.3f  ", motor_output);
	OLED_ShowString(30, 52, buffer, OLED_6X8);
	// start new conversion for next round
	ADC_Start();
}

void Periodic_10ms_ISR(void) {
	;
}

void Periodic_PID_ISR(void) {
	sint32 temps32 = Encoder_GetValue();
	if (!IO_DIP_Read(4)) {
	    float currentSpeed = (temps32 - last_encoder_value) * 1000.0 / PID_PERIOD_MS;
	    char buffer[25];
	    sprintf(buffer, "%.3f\r\n", currentSpeed);
	    while(Serial_Transmit((uint8*)buffer, strlen(buffer)));

		motor_output = PID_Output(&speed_pid, target_speed, (temps32 - last_encoder_value) * 1000.0 / PID_PERIOD_MS);
		last_encoder_value = temps32;
		Motor_Set(motor_output / 1000);
	} else {
		Motor_Set(0);
	}
}

void SWINT_User0_ISR(void) {
	;
}

void SWINT_User1_ISR(void) {
	;
}

void SWINT_User2_ISR(void) {
	;
}

void SWINT_User3_ISR(void) {
	;
}

void Serial_Received(uint8 *dataptr, uint32 length, uint8 tag) {
	switch (tag) {
	case 1:

		break;
	default:
		;
	}
}

void Bluetooth_Received(uint8 *dataptr, uint32 length, uint8 tag) {
	switch (tag) {
	case 1:

		break;
	default:
		;
	}
}

void Reed_Triggered(void) {
	;
}
